<?php
/**
 * All the post includes, these are here for performance reasons, (they can get compiled into the compiled bootstrap)
 */

/* These are included from the previous bootstrap files already.
Scanning /home/powellc/Projects/CorePlus/site/core/bootstrap.php...
Scanning /home/powellc/Projects/CorePlus/site/core/bootstrap_predefines.php...
Scanning /home/powellc/Projects/CorePlus/site/core/bootstrap_preincludes.php...
Scanning /home/powellc/Projects/CorePlus/site/core/functions/Core.functions.php...

Scanning /home/powellc/Projects/CorePlus/site/core/libs/filestore/File_Backend.interface.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/filestore/Directory_Backend.interface.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/filestore/FileContentFactory.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/filestore/backends/file_awss3.backend.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/filestore/backends/file_local.backend.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/filestore/backends/directory_local.backend.php...

Scanning /home/powellc/Projects/CorePlus/site/core/libs/cachecore/backends/icachecore.interface.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/cachecore/backends/cachecore.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/cachecore/backends/cachefile.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/cachecore/Cache.class.php...

Scanning /home/powellc/Projects/CorePlus/site/core/models/ComponentModel.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/models/PageModel.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/models/ConfigModel.class.php...

Scanning /home/powellc/Projects/CorePlus/site/core/libs/datamodel/DMI.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/datamodel/DMI_Backend.interface.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/datamodel/Dataset.class.php...

Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/ComponentFactory.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/ComponentHandler.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Component.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Component_2_1.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/ConfigHandler.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Controller.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Core.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Debug.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/HookHandler.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/InstallArchive.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/InstallArchiveAPI.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/InstallTask.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/ISingleton.interface.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Model.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Session.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/Time.class.php...
Scanning /home/powellc/Projects/CorePlus/site/core/libs/core/XMLLoader.class.php...
*/

// These are needed for smarty
define('SMARTY_DIR', ROOT_PDIR . 'core/libs/smarty/');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_internal_data.php');
require_once(ROOT_PDIR . 'core/libs/smarty/Smarty.class.php');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_internal_templatebase.php');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_internal_template.php');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_resource.php');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_internal_resource_file.php');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_cacheresource.php');
//require_once(ROOT_PDIR . 'core/libs/smarty/sysplugins/smarty_internal_cacheresource_file.php');
require_once(ROOT_PDIR . 'core/libs/core/CurrentPage.class.php');
require_once(ROOT_PDIR . 'core/libs/core/TemplateException.php');
require_once(ROOT_PDIR . 'core/libs/core/TemplateInterface.php');
require_once(ROOT_PDIR . 'core/libs/core/Template.class.php');
require_once(ROOT_PDIR . 'core/libs/core/UserAgent.php');
require_once(ROOT_PDIR . 'core/libs/core/View.class.php');
require_once(ROOT_PDIR . 'core/libs/core/ViewControl.class.php');
require_once(ROOT_PDIR . 'core/libs/core/Widget_2_1.class.php');
//require_once(ROOT_PDIR . 'core/functions/Core.functions.php');
//require_once(ROOT_PDIR . 'core/libs/datamodel/backends/mysqli.backend.php');
require_once(ROOT_PDIR . 'core/libs/core/Form.class.php');
//require_once(ROOT_PDIR . 'core/models/SessionModel.class.php');

require_once(ROOT_PDIR . 'core/libs/core/PageRequest.class.php');
require_once(ROOT_PDIR . 'core/libs/core/Controller_2_1.class.php');
require_once(ROOT_PDIR . 'core/models/WidgetModel.class.php');