<p class="message-note">
	Unable to write .htaccess directly.
</p>

<p>
	To ensure the site can utilize URLs correctly and to tweak apache's
	behaviour a little, a custom htaccess must be used.  The installer is unable to write to
	<?php echo ROOT_PDIR; ?>, so please copy the below contents into a file called ".htaccess" and
	click <a href="" class="button">Re-Check</a> when ready.
</p>

<textarea style="width:100%; height: 300px;"><?php echo $contents; ?>
</textarea>

<br/><br/>
<a href="" class="button">Re-Check</a>