<div class="preflightcheckstep">
	<?php foreach($tests as $test): ?>
		<p>
			<i class="check-<?php echo $test['status']; ?>" title="<?php echo $test['status']; ?>"></i>
			
			<span class="check-title"><?php echo $test['title']; ?></span>

			<span class="check-message"><?php echo $test['message']; ?></span>
		</p>
		<?php if(isset($test['fix']) && $test['fix']): ?>
			<div class="check-quickfix">
				<p><strong>Quick Fix: </strong> Execute the following in a shell window or contact your server administrator for assistance.</p>
				<pre><?php echo $test['fix']; ?></pre>
			</div>
		<?php endif; ?>
	<?php endforeach; ?>
</div>

<br/>

<a href="" class="button" style="float:left;">Re-Check</a>

<?php if($good): ?>
	<form action="" method="POST">
		<input type="submit" style="float:right;" value="Next &raquo;"/>
	</form>
<?php endif; ?>

<div class="clear"></div>