<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<link rel="stylesheet" href="assets/style.css"/>
		<script src="assets/jquery-1.7.1.min.js"></script>

		<title>Core Plus Installation Step <?php echo $step_current; ?> of <?php echo $step_total; ?></title>
	</head>

	<body>
		<div id="wrapper">
			<header>
				<img src="assets/logo.png" alt="Core Plus Installation"/><br/>
				<?php echo $title; ?>
			</header>
			
			<progress max="<?php echo $step_total; ?>" value="<?php echo $step_current; ?>" style="width:100%;"></progress>
			
			<section><?php echo $body; ?></section>
			
			<footer></footer>
		</div>
	</body>

</html>
