
TRUNCATE TABLE `geo_country`;
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AD', 'AND', 'Andorra');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AE', 'ARE', 'United Arab Emirates');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AF', 'AFG', 'Afghanistan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AG', 'ATG', 'Antigua and Barbuda');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AI', 'AIA', 'Anguilla');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AL', 'ALB', 'Albania');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AM', 'ARM', 'Armenia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AO', 'AGO', 'Angola');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AQ', 'ATA', 'Antarctica');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AR', 'ARG', 'Argentina');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AS', 'ASM', 'American Samoa');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AT', 'AUT', 'Austria');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AU', 'AUS', 'Australia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AW', 'ABW', 'Aruba');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AX', 'ALA', 'Åland Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('AZ', 'AZE', 'Azerbaijan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BA', 'BIH', 'Bosnia and Herzegovina');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BB', 'BRB', 'Barbados');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BD', 'BGD', 'Bangladesh');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BE', 'BEL', 'Belgium');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BF', 'BFA', 'Burkina Faso');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BG', 'BGR', 'Bulgaria');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BH', 'BHR', 'Bahrain');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BI', 'BDI', 'Burundi');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BJ', 'BEN', 'Benin');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BL', 'BLM', 'Saint Barthélemy');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BM', 'BMU', 'Bermuda');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BN', 'BRN', 'Brunei Darussalam');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BO', 'BOL', 'Bolivia, Plurinational State Of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BR', 'BRA', 'Brazil');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BS', 'BHS', 'Bahamas');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BT', 'BTN', 'Bhutan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BV', 'BVT', 'Bouvet Island');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BW', 'BWA', 'Botswana');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BY', 'BLR', 'Belarus');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('BZ', 'BLZ', 'Belize');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CA', 'CAN', 'Canada');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CC', 'CCK', 'Cocos (Keeling) Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CD', 'COD', 'Congo, The Democratic Republic Of The');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CF', 'CAF', 'Central African Republic');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CG', 'COG', 'Congo');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CH', 'CHE', 'Switzerland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CI', 'CIV', 'Côte D''Ivoire');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CK', 'COK', 'Cook Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CL', 'CHL', 'Chile');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CM', 'CMR', 'Cameroon');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CN', 'CHN', 'China');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CO', 'COL', 'Colombia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CR', 'CRI', 'Costa Rica');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CU', 'CUB', 'Cuba');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CV', 'CPV', 'Cape Verde');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CW', 'CUW', 'Curaçao');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CX', 'CXR', 'Christmas Island');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CY', 'CYP', 'Cyprus');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('CZ', 'CZE', 'Czech Republic');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('DE', 'DEU', 'Germany');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('DJ', 'DJI', 'Djibouti');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('DK', 'DNK', 'Denmark');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('DM', 'DMA', 'Dominica');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('DO', 'DOM', 'Dominican Republic');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('DZ', 'DZA', 'Algeria');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('EC', 'ECU', 'Ecuador');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('EE', 'EST', 'Estonia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('EG', 'EGY', 'Egypt');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('EH', 'ESH', 'Western Sahara');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ER', 'ERI', 'Eritrea');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ES', 'ESP', 'Spain');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ET', 'ETH', 'Ethiopia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('FI', 'FIN', 'Finland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('FJ', 'FJI', 'Fiji');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('FK', 'FLK', 'Falkland Islands  (Malvinas)');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('FM', 'FSM', 'Micronesia, Federated States Of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('FO', 'FRO', 'Faroe Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('FR', 'FRA', 'France');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GA', 'GAB', 'Gabon');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GB', 'GBR', 'United Kingdom');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GD', 'GRD', 'Grenada');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GE', 'GEO', 'Georgia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GF', 'GUF', 'French Guiana');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GG', 'GGY', 'Guernsey');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GH', 'GHA', 'Ghana');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GI', 'GIB', 'Gibraltar');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GL', 'GRL', 'Greenland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GM', 'GMB', 'Gambia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GN', 'GIN', 'Guinea');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GP', 'GLP', 'Guadeloupe');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GQ', 'GNQ', 'Equatorial Guinea');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GR', 'GRC', 'Greece');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GS', 'SGS', 'South Georgia and the South Sandwich Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GT', 'GTM', 'Guatemala');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GU', 'GUM', 'Guam');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GW', 'GNB', 'Guinea-Bissau');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('GY', 'GUY', 'Guyana');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('HK', 'HKG', 'Hong Kong');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('HM', 'HMD', 'Heard Island and McDonald Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('HN', 'HND', 'Honduras');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('HR', 'HRV', 'Croatia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('HT', 'HTI', 'Haiti');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('HU', 'HUN', 'Hungary');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ID', 'IDN', 'Indonesia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IE', 'IRL', 'Ireland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IL', 'ISR', 'Israel');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IM', 'IMN', 'Isle of Man');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IN', 'IND', 'India');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IO', 'IOT', 'British Indian Ocean Territory');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IQ', 'IRQ', 'Iraq');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IR', 'IRN', 'Iran, Islamic Republic Of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IS', 'ISL', 'Iceland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('IT', 'ITA', 'Italy');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('JE', 'JEY', 'Jersey');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('JM', 'JAM', 'Jamaica');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('JO', 'JOR', 'Jordan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('JP', 'JPN', 'Japan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KE', 'KEN', 'Kenya');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KG', 'KGZ', 'Kyrgyzstan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KH', 'KHM', 'Cambodia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KI', 'KIR', 'Kiribati');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KM', 'COM', 'Comoros');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KN', 'KNA', 'Saint Kitts And Nevis');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KP', 'PRK', 'Korea, Democratic People''s Republic Of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KR', 'KOR', 'Korea, Republic of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KW', 'KWT', 'Kuwait');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KY', 'CYM', 'Cayman Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('KZ', 'KAZ', 'Kazakhstan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LA', 'LAO', 'Lao People''s Democratic Republic');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LB', 'LBN', 'Lebanon');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LC', 'LCA', 'Saint Lucia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LI', 'LIE', 'Liechtenstein');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LK', 'LKA', 'Sri Lanka');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LR', 'LBR', 'Liberia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LS', 'LSO', 'Lesotho');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LT', 'LTU', 'Lithuania');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LU', 'LUX', 'Luxembourg');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LV', 'LVA', 'Latvia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('LY', 'LBY', 'Libya');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MA', 'MAR', 'Morocco');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MC', 'MCO', 'Monaco');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MD', 'MDA', 'Moldova, Republic of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ME', 'MNE', 'Montenegro');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MF', 'MAF', 'Saint Martin (French Part)');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MG', 'MDG', 'Madagascar');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MH', 'MHL', 'Marshall Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MK', 'MKD', 'Macedonia, the Former Yugoslav Republic Of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ML', 'MLI', 'Mali');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MM', 'MMR', 'Myanmar');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MN', 'MNG', 'Mongolia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MO', 'MAC', 'Macao');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MP', 'MNP', 'Northern Mariana Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MQ', 'MTQ', 'Martinique');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MR', 'MRT', 'Mauritania');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MS', 'MSR', 'Montserrat');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MT', 'MLT', 'Malta');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MU', 'MUS', 'Mauritius');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MV', 'MDV', 'Maldives');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MW', 'MWI', 'Malawi');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MX', 'MEX', 'Mexico');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MY', 'MYS', 'Malaysia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('MZ', 'MOZ', 'Mozambique');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NA', 'NAM', 'Namibia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NC', 'NCL', 'New Caledonia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NE', 'NER', 'Niger');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NF', 'NFK', 'Norfolk Island');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NG', 'NGA', 'Nigeria');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NI', 'NIC', 'Nicaragua');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NL', 'NLD', 'Netherlands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NO', 'NOR', 'Norway');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NP', 'NPL', 'Nepal');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NR', 'NRU', 'Nauru');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NU', 'NIU', 'Niue');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('NZ', 'NZL', 'New Zealand');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('OM', 'OMN', 'Oman');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PA', 'PAN', 'Panama');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PE', 'PER', 'Peru');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PF', 'PYF', 'French Polynesia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PG', 'PNG', 'Papua New Guinea');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PH', 'PHL', 'Philippines');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PK', 'PAK', 'Pakistan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PL', 'POL', 'Poland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PM', 'SPM', 'Saint Pierre And Miquelon');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PN', 'PCN', 'Pitcairn');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PR', 'PRI', 'Puerto Rico');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PS', 'PSE', 'Palestinian Territory, Occupied');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PT', 'PRT', 'Portugal');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PW', 'PLW', 'Palau');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('PY', 'PRY', 'Paraguay');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('QA', 'QAT', 'Qatar');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('RE', 'REU', 'Réunion');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('RO', 'ROU', 'Romania');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('RS', 'SRB', 'Serbia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('RU', 'RUS', 'Russian Federation');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('RW', 'RWA', 'Rwanda');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SA', 'SAU', 'Saudi Arabia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SB', 'SLB', 'Solomon Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SC', 'SYC', 'Seychelles');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SD', 'SDN', 'Sudan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SE', 'SWE', 'Sweden');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SG', 'SGP', 'Singapore');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SH', 'SHN', 'Saint Helena, Ascension and Tristan Da Cunha');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SI', 'SVN', 'Slovenia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SJ', 'SJM', 'Svalbard And Jan Mayen');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SK', 'SVK', 'Slovakia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SL', 'SLE', 'Sierra Leone');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SM', 'SMR', 'San Marino');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SN', 'SEN', 'Senegal');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SO', 'SOM', 'Somalia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SR', 'SUR', 'Suriname');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SS', 'SSD', 'South Sudan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ST', 'STP', 'Sao Tome and Principe');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SV', 'SLV', 'El Salvador');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SX', 'SXM', 'Sint Maarten (Dutch part)');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SY', 'SYR', 'Syrian Arab Republic');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('SZ', 'SWZ', 'Swaziland');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TC', 'TCA', 'Turks and Caicos Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TD', 'TCD', 'Chad');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TF', 'ATF', 'French Southern Territories');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TG', 'TGO', 'Togo');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TH', 'THA', 'Thailand');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TJ', 'TJK', 'Tajikistan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TK', 'TKL', 'Tokelau');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TL', 'TLS', 'Timor-Leste');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TM', 'TKM', 'Turkmenistan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TN', 'TUN', 'Tunisia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TO', 'TON', 'Tonga');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TR', 'TUR', 'Turkey');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TT', 'TTO', 'Trinidad and Tobago');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TV', 'TUV', 'Tuvalu');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TW', 'TWN', 'Taiwan, Province Of China');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('TZ', 'TZA', 'Tanzania, United Republic of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('UA', 'UKR', 'Ukraine');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('UG', 'UGA', 'Uganda');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('UM', 'UMI', 'United States Minor Outlying Islands');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('US', 'USA', 'United States');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('UY', 'URY', 'Uruguay');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('UZ', 'UZB', 'Uzbekistan');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VA', 'VAT', 'Holy See (Vatican City State)');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VC', 'VCT', 'Saint Vincent And The Grenadines');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VE', 'VEN', 'Venezuela, Bolivarian Republic of');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VG', 'VGB', 'Virgin Islands, British');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VI', 'VIR', 'Virgin Islands, U.S.');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VN', 'VNM', 'Viet Nam');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('VU', 'VUT', 'Vanuatu');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('WF', 'WLF', 'Wallis and Futuna');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('WS', 'WSM', 'Samoa');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('YE', 'YEM', 'Yemen');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('YT', 'MYT', 'Mayotte');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ZA', 'ZAF', 'South Africa');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ZM', 'ZMB', 'Zambia');
INSERT INTO `geo_country` (`iso2`, `iso3`, `name`) VALUES('ZW', 'ZWE', 'Zimbabwe');
